# -*- coding: utf-8 -*-
"""
referencia_atributos.py -- el set de referencia etiquetado a mano con el que
se mide si la clasificacion entiende QUE es cada producto.

Cada entrada es un producto REAL del catalogo de Centro de Costos (solo su
nombre y descripcion: sin montos, proveedores ni numeros de documento, igual
que los tests de taxonomia) con lo que un comprador diria que es:

    familia    -- "Planchas", "Fittings", "Pernos"...
    tipo       -- "Plancha", "Codo", "Perno Hexagonal"...
    material   -- el material CONSTITUTIVO ("Policarbonato", "Acero
                  inoxidable"); None si el texto no lo dice. SALTAR = no se
                  evalua (el texto es genuinamente ambiguo).
    dims       -- {rol: valor}. Valor en mm ("0.7mm") o en pulgadas ('1/2"').
                  Solo se etiquetan las dimensiones de las que no hay duda.
    specs      -- {clave: valor} de especificaciones tecnicas (opcional).

Por que existe: hasta 2026-09-22 la unica medicion del modulo era el
benchmark del buscador, y ese juzga los resultados con la clasificacion del
propio sistema. Si la clasificacion se equivoca (una plancha de policarbonato
dentro de "Perfileria y Maderas", tres barras PEX de 16, 20 y 32 mm en una
sola hoja), el benchmark no lo ve. Este set es independiente del sistema: se
escribio mirando el producto, no la salida del clasificador.

Uso: ver evaluacion.py (py -3.14 driver.py evaluacion).
"""

SALTAR = object()


def R(nombre, descripcion, familia, tipo, material=None, dims=None, specs=None,
      categoria=None, terminacion=None):
    return {"nombre": nombre, "descripcion": descripcion, "familia": familia,
            "tipo": tipo, "material": material, "dims": dims or {},
            "specs": specs or {}, "categoria": categoria, "terminacion": terminacion}


REFERENCIA = [
    # ------------------------------------------------------------ Planchas
    R("Plancha policarbonato", "Plancha policarbonato transparente 0,7 x 812 x 3660 mm",
      "Planchas", "Plancha", "Policarbonato",
      {"espesor": "0.7mm", "ancho": "812mm", "largo": "3660mm"},
      categoria="Planchas y Perfiles", terminacion="Transparente"),
    R("Policarbonato", "Plancha policarbonato 4mm",
      "Planchas", "Plancha", "Policarbonato", {"espesor": "4mm"}),
    R("Plancha", "Plancha galvanizada lisa 0,8 x 1000 x 3000 mm",
      "Planchas", "Plancha", "Acero galvanizado",
      {"espesor": "0.8mm", "ancho": "1000mm", "largo": "3000mm"}, terminacion="Lisa"),
    R("Plancha", "Plancha de acero 2,5 x 1000 x 3000 mm ASTM A-36",
      "Planchas", "Plancha", "Acero carbono",
      {"espesor": "2.5mm", "ancho": "1000mm", "largo": "3000mm"}, specs={"grado": "ASTM A36"}),
    R("Plancha", "Plancha laminada en frío 1010, 1,0 mm x 1,0 x 3,0 m",
      "Planchas", "Plancha", "Acero carbono",
      {"espesor": "1mm", "ancho": "1000mm", "largo": "3000mm"},
      specs={"grado": "SAE 1010"}, terminacion="Laminada en frío"),
    R("Plancha zincalum", "Plancha zincalum P11 economico 0,35 x 851 x 3660 mm",
      "Planchas", "Plancha", "Zincalum",
      {"espesor": "0.35mm", "ancho": "851mm", "largo": "3660mm"}),
    R("Placa inox", "Placa inox. 1mm", "Planchas", "Plancha", "Acero inoxidable",
      {"espesor": "1mm"}),
    R("Plancha", "Plancha graphinox 1/16 x 1mt x 1mt (con descuento)",
      "Empaquetaduras", "Plancha de Empaquetadura", "Grafito",
      {"espesor": '1/16"', "ancho": "1000mm", "largo": "1000mm"}),
    R("Plancha teflon", "Plancha teflón expandido 1/8 x 1,5mt x 1,5mt (0,06 planchas)",
      "Empaquetaduras", "Plancha de Empaquetadura", "PTFE",
      {"espesor": '1/8"', "ancho": "1500mm", "largo": "1500mm"}),
    R("EPDM", "EPDM 3/16 x 1,5 MT (precio de lista por metro con descuento aplicado)",
      "Empaquetaduras", "Plancha de Empaquetadura", "EPDM", {"espesor": '3/16"'}),

    # ------------------------------------------------------------ Perfiles
    R("Perfil", "Perfil cuadrado 40 x 40 x 2 mm x 6 m",
      "Perfiles", "Perfil Cuadrado", None,
      {"ancho": "40mm", "alto": "40mm", "espesor": "2mm", "largo": "6000mm"}),
    R("Perfil cuadrado", "Perfil cuadrado 40x40x2.0mm, 6 metros",
      "Perfiles", "Perfil Cuadrado", None,
      {"ancho": "40mm", "alto": "40mm", "espesor": "2mm", "largo": "6000mm"}),
    R("Perfil rectangular", "Perfil rectangular 80x40x3.0mm",
      "Perfiles", "Perfil Rectangular", None,
      {"ancho": "80mm", "alto": "40mm", "espesor": "3mm"}),
    R("Tubo cuadrado", "Tubo cuad neg 40x2mm", "Perfiles", "Perfil Cuadrado", "Acero negro",
      {"ancho": "40mm", "alto": "40mm", "espesor": "2mm"}),
    R("Tubo cuadrado", "Tubo cuad neg 30x2mm", "Perfiles", "Perfil Cuadrado", "Acero negro",
      {"ancho": "30mm", "alto": "30mm", "espesor": "2mm"}),
    R("Tubo cuadrado", "Tubo cuad neg 50x3mm", "Perfiles", "Perfil Cuadrado", "Acero negro",
      {"ancho": "50mm", "alto": "50mm", "espesor": "3mm"}),
    R("Angulo", "Angulo lam 40x40x3mm", "Perfiles", "Perfil Ángulo", None,
      {"ancho": "40mm", "alto": "40mm", "espesor": "3mm"}),
    R("Platina", "Platina 25x3mm", "Barras y Platinas", "Platina", None,
      {"ancho": "25mm", "espesor": "3mm"}),
    R("Platina", "Platina 25x3, 2 metros", "Barras y Platinas", "Platina", None,
      {"ancho": "25mm", "espesor": "3mm", "largo": "2000mm"}),
    R("Pletina", "Pletina 50x5mm", "Barras y Platinas", "Platina", None,
      {"ancho": "50mm", "espesor": "5mm"}),
    R("Riel", "Riel RUC galvanizado en caliente (HDG) 30 micras, 42 x 42 x 2,0 x 3000 mm",
      "Perfiles", "Riel", "Acero galvanizado",
      {"ancho": "42mm", "alto": "42mm", "espesor": "2mm", "largo": "3000mm"},
      terminacion="Galvanizado en caliente"),
    R("Moldura", "Moldura 20x10mmx2m", "Perfiles", "Moldura", None,
      {"ancho": "20mm", "alto": "10mm", "largo": "2000mm"}),
    R("Fierro", "Fierro construcción 8mm", "Barras y Platinas", "Fierro de Construcción",
      "Acero carbono", {"diametro": "8mm"}),
    R("Malla", "Cerco (panel de malla) galvanizado RG5020 x 2,7 mm, 1 x 2 m",
      "Mallas", "Malla", "Acero galvanizado",
      {"diametro": "2.7mm", "ancho": "1000mm", "largo": "2000mm"}),

    # ------------------------------------------------------------ Maderas
    R("Pino bruto", 'Pino verde bruto 2"x3"x3,20mt', "Maderas", "Madera Dimensionada", "Pino",
      {"ancho": '2"', "alto": '3"', "largo": "3200mm"}),
    R("Pino bruto", 'Pino verde bruto 1"x5"x3,20mt', "Maderas", "Madera Dimensionada", "Pino",
      {"ancho": '1"', "alto": '5"', "largo": "3200mm"}),
    R("Pino cepillado", "Pino seco cepillado 2x6 3,2 mt", "Maderas", "Madera Dimensionada", "Pino",
      {"ancho": '2"', "alto": '6"', "largo": "3200mm"}),
    R("Pino cepillado", "Pino seco cepillado 1x6 3,2 mt", "Maderas", "Madera Dimensionada", "Pino",
      {"ancho": '1"', "alto": '6"', "largo": "3200mm"}),
    R("Pino cepillado", "Pino seco cepillado 2x4, 3.2m", "Maderas", "Madera Dimensionada", "Pino",
      {"ancho": '2"', "alto": '4"', "largo": "3200mm"}),
    R("Pino dimensionado", "Pino dimensionado verde 2x3, 3.2m", "Maderas", "Madera Dimensionada",
      "Pino", {"ancho": '2"', "alto": '3"', "largo": "3200mm"}),
    R("Viga de pino", "Viga pino 2x6 4,8 mt", "Maderas", "Madera Dimensionada", "Pino",
      {"ancho": '2"', "alto": '6"', "largo": "4800mm"}),
    R("Viga de pino", "Viga pino 2x6, 4.8m", "Maderas", "Madera Dimensionada", "Pino",
      {"ancho": '2"', "alto": '6"', "largo": "4800mm"}),

    # ------------------------------------------------------------ Cañerías y tubos
    R("Caneria", "Caneria ERW ASTM A53 GR B 8 pulgadas", "Cañerías y Tubos", "Cañería",
      "Acero negro", {"diametro": '8"'}, specs={"norma": "ASTM A53"}),
    R("Caneria de cobre", 'Caneria de cobre tipo M para agua, 1", tira de 6 mt',
      "Cañerías y Tubos", "Cañería", "Cobre", {"diametro": '1"', "largo": "6000mm"},
      specs={"tipo_pared": "Tipo M"}),
    R("Canieria cobre", "Cañería L cobre (06) 1.1/2 plg, 6 MT", "Cañerías y Tubos", "Cañería",
      "Cobre", {"diametro": '1.1/2"', "largo": "6000mm"}, specs={"tipo_pared": "Tipo L"}),
    R("Canieria cobre", "Cañería L cobre (05) 1.1/4 plg", "Cañerías y Tubos", "Cañería", "Cobre",
      {"diametro": '1.1/4"'}, specs={"tipo_pared": "Tipo L"}),
    R("Canieria negra", "Cañería negra ASTM A-53 (04) 3/4 plg, 6 MTS", "Cañerías y Tubos",
      "Cañería", "Acero negro", {"diametro": '3/4"', "largo": "6000mm"}),
    R("Cañeria PEX", "PEX-A Aqualine 32 barra 5.8mts", "Cañerías y Tubos", "Cañería", "PEX",
      {"diametro": "32mm", "largo": "5800mm"}),
    R("Cañeria PEX", "PEX-A Aqualine 20 barra 5.8mt", "Cañerías y Tubos", "Cañería", "PEX",
      {"diametro": "20mm", "largo": "5800mm"}),
    R("Cañeria PEX", "PEX-A Aqualine 16 barra 5.8mt", "Cañerías y Tubos", "Cañería", "PEX",
      {"diametro": "16mm", "largo": "5800mm"}),
    R("Cañeria PPR", "Cañeria PPR serie 3.2 (PN-16) 040x5.5, 5.8m", "Cañerías y Tubos",
      "Cañería", "PPR", {"diametro": "40mm", "espesor": "5.5mm", "largo": "5800mm"},
      specs={"presion": "PN16"}),
    R("Tuberia PPR", "PPR serie 3.2 (PN-16) 032x4.4 5.8m", "Cañerías y Tubos", "Cañería", "PPR",
      {"diametro": "32mm", "espesor": "4.4mm", "largo": "5800mm"}, specs={"presion": "PN16"}),
    R("Tubería", "Tubería PPR Beta 90mm PN16, 6 metros", "Cañerías y Tubos", "Cañería", "PPR",
      {"diametro": "90mm", "largo": "6000mm"}, specs={"presion": "PN16"}),
    R("Cañeria de cobre", "Cañeria de cobre tipo L 1/2 x 1 metro", "Cañerías y Tubos", "Cañería",
      "Cobre", {"diametro": '1/2"', "largo": "1000mm"}, specs={"tipo_pared": "Tipo L"}),
    R("Cañería", 'Cañería de acero inoxidable con costura ASTM A312 304L, 6" SCH10S '
      '(espesor 3,40 mm), config. I/I-PB/PB, tira de 6 m, proceso CCH.',
      "Cañerías y Tubos", "Cañería", "Acero inoxidable",
      {"diametro": '6"', "espesor": "3.4mm", "largo": "6000mm"},
      specs={"schedule": "SCH 10S", "grado": "AISI 304L"}),
    R("Tuberia", "Tuberia PVC 32mm PN-10", "Cañerías y Tubos", "Cañería", "PVC",
      {"diametro": "32mm"}, specs={"presion": "PN10"}),
    R("Tubo", "Tubo 1/4 acero inoxidable 316 x 6mts, cod. TUSS04-TS. Entrega en mesón, "
      "cortada en 3 mts", "Cañerías y Tubos", "Tubo", "Acero inoxidable",
      {"diametro": '1/4"', "largo": "6000mm"}, specs={"grado": "AISI 316"}),
    R("Tubo PVC", "Tubo PVC presión 25mm x 1mt", "Cañerías y Tubos", "Tubo", "PVC",
      {"diametro": "25mm", "largo": "1000mm"}),
    R("Tubo PVC", "Tubo PVC hidraulico 32mm 1mt PN-10", "Cañerías y Tubos", "Tubo", "PVC",
      {"diametro": "32mm", "largo": "1000mm"}, specs={"presion": "PN10"}),
    R("Cañería", "Cañería tipo L tiras", "Cañerías y Tubos", "Cañería", "Cobre",
      specs={"tipo_pared": "Tipo L"}),
    R("Cañería", 'Cañería de cobre recta tipo K 3/4", venta por metro (18 m)',
      "Cañerías y Tubos", "Cañería", "Cobre", {"diametro": '3/4"'},
      specs={"tipo_pared": "Tipo K"}),

    # ------------------------------------------------------------ Válvulas
    R("Valvula bola", "Válvula bola italiana p/estopa Enolgas (08) 2 plg", "Válvulas",
      "Válvula de Bola", None, {"diametro": '2"'}),
    R("Válvula", 'Válvula bola Bugatti P/T 2" HI-HI M/MET', "Válvulas", "Válvula de Bola", None,
      {"diametro": '2"'}, specs={"conexion": "HI-HI"}),
    R("Valvula bola", "Valvula bola DZR hilo interior-hilo interior 1 1/2", "Válvulas",
      "Válvula de Bola", "Latón", {"diametro": '1.1/2"'}),
    R('Valvula bola HD DZR PN30 HI-HI 3/4" M/L Anwo', "Cod. 20.060.61DZR", "Válvulas",
      "Válvula de Bola", "Latón", {"diametro": '3/4"'}, specs={"presion": "PN30"}),
    R("Válvula", 'Válvula de bola 3/4", inoxidable, paso total', "Válvulas", "Válvula de Bola",
      "Acero inoxidable", {"diametro": '3/4"'}),
    R("Válvula de bola", "Válvula de bola paso 3/4 de acero", "Válvulas", "Válvula de Bola",
      "Acero carbono", {"diametro": '3/4"'}),
    R("Valvula", "Valvula bola PPR 032", "Válvulas", "Válvula de Bola", "PPR",
      {"diametro": "32mm"}),
    R("Válvula bola", "Válvula bola PPR 50mm 2UA fusión/fusión", "Válvulas", "Válvula de Bola",
      "PPR", {"diametro": "50mm"}),
    R("Válvula", "Válvula aguja inoxidable 1/4 OD 5000 PSI, cod. VASS04OD-DL", "Válvulas",
      "Válvula de Aguja", "Acero inoxidable", {"diametro": '1/4"'},
      specs={"presion": "5000 psi"}),
    R("Válvula", "Válvula retención c/resorte inoxidable 3/8, cod. VRYSS06-CW", "Válvulas",
      "Válvula de Retención", "Acero inoxidable", {"diametro": '3/8"'}),
    R("Válvula", 'Válvula retención vertical disco bronce Dura Plus 1"', "Válvulas",
      "Válvula de Retención", "Bronce", {"diametro": '1"'}),
    R("Valvula retencion", "Válvula retención vertical Bugatti 2 A/BR HI HI", "Válvulas",
      "Válvula de Retención", SALTAR, {"diametro": '2"'}),
    R("Valvula de alivio", "Valvula de alivio 3/4, 3 bar", "Válvulas", "Válvula de Alivio", None,
      {"diametro": '3/4"'}, specs={"presion": "3 bar"}),
    R("Válvula corte", "Válvula corte 3/4", "Válvulas", "Válvula de Corte", None,
      {"diametro": '3/4"'}),
    R('Valvula de bloqueo y purga BBV 10000PSI 1/4"N', "Cod. VBPSS0410000", "Válvulas",
      "Válvula de Bloqueo y Purga", None, {"diametro": '1/4"'},
      specs={"presion": "10000 psi"}),
    R("Valvula fancoil", 'Válvula fancoil Honeywell, retorno por resorte 3/4", dos vías, '
      "conexión por surt, código 00.129.03KH", "Válvulas", "Válvula Fancoil", None,
      {"diametro": '3/4"'}),
    R("Kit valvula termostatica", "Kit valvula termostatica angular 1/2 PEX EK (incluye valvula "
      "solo cuerpo y cabezal termostatico IVAR)", "Válvulas", "Válvula Termostática", SALTAR,
      {"diametro": '1/2"'}),
    R("Filtro", 'Filtro tipo Y, acero inoxidable, 3/4"', "Filtros", "Filtro Y",
      "Acero inoxidable", {"diametro": '3/4"'}),
    R("Filtro", 'Filtro tipo Y bronce 3/4"', "Filtros", "Filtro Y", "Bronce",
      {"diametro": '3/4"'}),
    R("Purga automática", 'Purga automática 1/2"', "Purgas y Venteos", "Purga", None,
      {"diametro": '1/2"'}),
    R("Canastillo", "Canastillo A inox italiano 3 plg", "Filtros", "Canastillo",
      "Acero inoxidable", {"diametro": '3"'}),

    # ------------------------------------------------------------ Fittings
    R("Codo", "Codo SO-SO 1 1/4 bronce", "Fittings", "Codo", "Bronce", {"diametro": '1.1/4"'}),
    R("Codo", "Codo PPR 90 032", "Fittings", "Codo", "PPR", {"diametro": "32mm"},
      specs={"angulo": "90°"}),
    R("Codo", 'Codo SO SO cobre 1"', "Fittings", "Codo", "Cobre", {"diametro": '1"'}),
    R("Codo", "Codo BR 90 3/4 SO/HE", "Fittings", "Codo", "Bronce", {"diametro": '3/4"'},
      specs={"angulo": "90°"}),
    R("Codo", "Codo PVC-P 90 25mm cementar", "Fittings", "Codo", "PVC", {"diametro": "25mm"}),
    R("Codo", "Codo RL45 A234 WPB STD BW 8 pulgadas", "Fittings", "Codo", "Acero carbono",
      {"diametro": '8"'}, specs={"schedule": "STD"}),
    R("Codo", 'Codo unión inoxidable 3/4"', "Fittings", "Codo", "Acero inoxidable",
      {"diametro": '3/4"'}),
    R("Codo", 'Codo 90° DZR PEX HE 20x3/4"', "Fittings", "Codo", "Latón",
      {"diametro": "20mm", "diametro_salida": '3/4"'}),
    R("Codo 45 galvanizado 1/2", "Cod. 4508C150-JM", "Fittings", "Codo", "Acero galvanizado",
      {"diametro": '1/2"'}, specs={"angulo": "45°"}),
    R("Codo 90 galvanizado 1 NPT", "Cod. 988300064", "Fittings", "Codo", "Acero galvanizado",
      {"diametro": '1"'}, specs={"rosca": "NPT"}),
    R("Codo bronce", "Codo SO BR (05) 1.1/4 plg", "Fittings", "Codo", "Bronce",
      {"diametro": '1.1/4"'}),
    R("Curva", "Curva mandrilada SCH40 A234 (02) 3/4 plg", "Fittings", "Curva", "Acero carbono",
      {"diametro": '3/4"'}, specs={"schedule": "SCH 40"}),
    R("Tee", "Tee mandrilada SCH40 A234 (02) 3/4 plg", "Fittings", "Tee", "Acero carbono",
      {"diametro": '3/4"'}, specs={"schedule": "SCH 40"}),
    R("Tee", "Tee PPR 90x40x90mm PN20", "Fittings", "Tee", "PPR",
      {"diametro": "90mm", "diametro_derivacion": "40mm"}, specs={"presion": "PN20"}),
    R("Tee", 'Tee de bronce 3/4" x 3/4" x 1/2" SO x SO x HI (soldar x soldar x hilo interior)',
      "Fittings", "Tee", "Bronce", {"diametro": '3/4"', "diametro_derivacion": '1/2"'}),
    R("Tee reductora", "Tee reduc SO BR 2x3/4 plg", "Fittings", "Tee", "Bronce",
      {"diametro": '2"', "diametro_derivacion": '3/4"'}),
    R("Tee hembra inoxidable 1/2", "Cod. 101SS08C150-SB", "Fittings", "Tee", "Acero inoxidable",
      {"diametro": '1/2"'}),
    R("Tee galv. 1 NPT", "Cod. 988500064", "Fittings", "Tee", "Acero galvanizado",
      {"diametro": '1"'}, specs={"rosca": "NPT"}),
    R("Copla", "Copla PPR 032", "Fittings", "Copla", "PPR", {"diametro": "32mm"}),
    R("Copla", "Copla acero inoxidable 1/4 NPT 3000 psi, cod. 103SS04C3000-", "Fittings", "Copla",
      "Acero inoxidable", {"diametro": '1/4"'}, specs={"rosca": "NPT", "presion": "3000 psi"}),
    R("Copla", "Copla SO-SO 1 1/4x1 bronce", "Fittings", "Copla", "Bronce",
      {"diametro": '1.1/4"', "diametro_salida": '1"'}),
    R("Copla reducción", "Copla reducción PPR 50x40mm PN20", "Fittings", "Copla", "PPR",
      {"diametro": "50mm", "diametro_salida": "40mm"}, specs={"presion": "PN20"}),
    R("Copla PVC", "Copla PVC cementada de 50 mm", "Fittings", "Copla", "PVC",
      {"diametro": "50mm"}),
    R("Copla", "Copla reduc galv tupy 07 1x3/4", "Fittings", "Copla", "Acero galvanizado",
      {"diametro": '1"', "diametro_salida": '3/4"'}),
    R("Copla", "Copla fe soldable HI NPT 02 1.1/4", "Fittings", "Copla", "Acero carbono",
      {"diametro": '1.1/4"'}, specs={"rosca": "NPT"}),
    R("Bushing", 'Bushing galvanizado 1 1/4"x1"', "Fittings", "Bushing", "Acero galvanizado",
      {"diametro": '1.1/4"', "diametro_salida": '1"'}),
    R("Bushing", "Bushing inoxidable 3/4 X 1/2 NPT 3000 psi, cod. 110SS1208C300, cantidad 2",
      "Fittings", "Bushing", "Acero inoxidable",
      {"diametro": '3/4"', "diametro_salida": '1/2"'}, specs={"rosca": "NPT"}),
    R("Bushing", "Bushing de bronce para agua 1/2 HE x 3/8 HI", "Fittings", "Bushing", "Bronce",
      {"diametro": '1/2"', "diametro_salida": '3/8"'}),
    R("Buje", "Buje red larga PVC-P 32x25 cementar", "Fittings", "Bushing", "PVC",
      {"diametro": "32mm", "diametro_salida": "25mm"}),
    R("Niple galvanizado", "Niple galvanizado ISO BSP-BSP 08cm (09) 1.1/2 plg", "Fittings",
      "Niple", "Acero galvanizado", {"diametro": '1.1/2"', "largo": "80mm"},
      specs={"rosca": "BSP"}),
    R("Niple", "Niple bronce 1/2 HE HE", "Fittings", "Niple", "Bronce", {"diametro": '1/2"'}),
    R("Niple", "Niple TUE BR 1/2x3/4 HE/NI", "Fittings", "Niple", "Bronce",
      {"diametro": '1/2"', "diametro_salida": '3/4"'}),
    R("Punta negra", "Punta negra ASTM BSP (03) 3/4x10cm", "Fittings", "Punta Negra",
      "Acero negro", {"diametro": '3/4"', "largo": "100mm"}),
    R("Punta", "Punta neg astm bsp 04 1x10cms", "Fittings", "Punta Negra", "Acero negro",
      {"diametro": '1"', "largo": "100mm"}),
    R("Hilo tuerca", "Hilo tuerca galv tupy 04 3/4", "Fittings", "Hilo Tuerca",
      "Acero galvanizado", {"diametro": '3/4"'}),
    R("Hilo tuerca", "Hilo tuerca BR (09) 2 plg", "Fittings", "Hilo Tuerca", "Bronce",
      {"diametro": '2"'}),
    R("Terminal", "Terminal DZR PEX HE 32x1 (5 pcs/bag)", "Fittings", "Terminal", "Latón",
      {"diametro": "32mm", "diametro_salida": '1"'}),
    R("Terminal PEX", "Terminal Eurokono PEX 20", "Fittings", "Terminal", SALTAR,
      {"diametro": "20mm"}),
    R("Terminal", "Terminal PPR HI 032x1 injerto metalico", "Fittings", "Terminal", "PPR",
      {"diametro": "32mm", "diametro_salida": '1"'}),
    R("Terminal", 'Terminal HI PPR 50x1 1/2" PN20', "Fittings", "Terminal", "PPR",
      {"diametro": "50mm", "diametro_salida": '1.1/2"'}),
    R("Terminal", "Terminal de bronce soldar / hilo interior 1/2", "Fittings", "Terminal",
      "Bronce", {"diametro": '1/2"'}),
    R("Termo", "Termo SO HI BR 3 plg", "Fittings", "Terminal", "Bronce", {"diametro": '3"'}),
    R("Terminal PVC", "Terminal presión cementar/hembra 25 x 3/4", "Fittings", "Terminal", "PVC",
      {"diametro": "25mm", "diametro_salida": '3/4"'}),
    R("Unión americana", "Unión americana PPR fusión/fusión 32mm", "Fittings", "Unión Americana",
      "PPR", {"diametro": "32mm"}),
    R("Union americana", "U Amer Aj Br galvanizada Mecha (08) 2 plg", "Fittings",
      "Unión Americana", SALTAR, {"diametro": '2"'}),
    R("Union americana", 'Union Americana PPR HE D32x1"', "Fittings", "Unión Americana", "PPR",
      {"diametro": "32mm", "diametro_salida": '1"'}),
    R("Unión", "Unión recta inoxidable 1/4, cod. 762FSS04-DL", "Fittings", "Unión",
      "Acero inoxidable", {"diametro": '1/4"'}),
    R("Machon", 'Machon DZR 1/2" HE (5 pcs/bag)', "Fittings", "Machón", "Latón",
      {"diametro": '1/2"'}),
    R("Flange", "Flange Slip-On ASTM A105 8 pulgadas", "Flanges", "Flange", "Acero carbono",
      {"diametro": '8"'}),
    R("Flange", "Flange DN50 PN16, código 00.176.02", "Flanges", "Flange", None,
      {"diametro": '2"'}, specs={"presion": "PN16"}),
    R("Flange", "Flange DIN HI BSP 1.1/4 plg", "Flanges", "Flange", None,
      {"diametro": '1.1/4"'}, specs={"rosca": "BSP"}),
    R("Reducción cobre", "Reducción cobre 3/4 x 1/2 Koalition", "Fittings", "Reducción", "Cobre",
      {"diametro": '3/4"', "diametro_salida": '1/2"'}),
    R("Tapagorro", "Tapagorro PPR 40mm PN20", "Fittings", "Tapón", "PPR", {"diametro": "40mm"}),
    R("Tapa gorro", 'Tapa gorro soldar 1" bronce', "Fittings", "Tapón", "Bronce",
      {"diametro": '1"'}),
    R("Tapón", "Tapón macho inoxidable 1/4 NPT 3000 PSI, cod. 121SS04C3000-", "Fittings", "Tapón",
      "Acero inoxidable", {"diametro": '1/4"'}, specs={"rosca": "NPT"}),
    R("Conector", "Conector hembra inoxidable 1/2x3/8, cod. 766FSS0806-DL, cantidad 2",
      "Fittings", "Conector", "Acero inoxidable",
      {"diametro": '1/2"', "diametro_salida": '3/8"'}),
    R("Adaptador bronce", "Adaptador bronce 1/4' HI NPT - 1/8' HE NPT, código FIB1401800",
      "Fittings", "Adaptador", "Bronce", {"diametro": '1/4"', "diametro_salida": '1/8"'}),
    R("Abrazadera", "Abrazadera PPR 32mm", "Soportes y Abrazaderas", "Abrazadera", "PPR",
      {"diametro": "32mm"}),
    R("Abrazadera", 'Abrazadera RUC galvanizada con perno y tuerca, 3/4" - 1,5 mm (25 mm)',
      "Soportes y Abrazaderas", "Abrazadera", "Acero galvanizado",
      {"diametro": '3/4"', "espesor": "1.5mm"}),
    R("Flexible", 'Flexible calef HI/HI 1/2" 40cm', "Mangueras y Flexibles", "Flexible", None,
      {"diametro": '1/2"', "largo": "400mm"}),
    R("Flexible", "Flexible HI-HI 30 cm acero inoxidable metalico para agua",
      "Mangueras y Flexibles", "Flexible", "Acero inoxidable", {"largo": "300mm"}),

    # ------------------------------------------------------------ Pernos y fijaciones
    R("Perno", 'Perno hexagonal zincado GR.2 UNC 5/8-11 x 5"', "Pernos", "Perno Hexagonal",
      "Acero galvanizado", {"diametro": '5/8"', "largo": '5"'},
      specs={"grado": "G-2", "rosca": "UNC"}),
    R("Perno hexagonal", "Perno hexagonal G-2 (30) 5x5/8 plg", "Pernos", "Perno Hexagonal",
      "Acero carbono", {"diametro": '5/8"', "largo": '5"'}, specs={"grado": "G-2"}),
    R("Perno hexagonal", "Perno hexagonal G-2 (10) 2.1/2x5/8 plg", "Pernos", "Perno Hexagonal",
      "Acero carbono", {"diametro": '5/8"', "largo": '2.1/2"'}, specs={"grado": "G-2"}),
    R("Perno hexagonal", "Perno hexagonal G-5 negro UNC 1/2 x 3", "Pernos", "Perno Hexagonal",
      "Acero carbono", {"diametro": '1/2"', "largo": '3"'},
      specs={"grado": "G-5", "rosca": "UNC"}, terminacion="Negro"),
    R("Perno", "Perno hex zincado 3/4x3 1/2", "Pernos", "Perno Hexagonal", "Acero galvanizado",
      {"diametro": '3/4"', "largo": '3.1/2"'}),
    R("Perno", "Perno anclaje 1/2x5 1/2", "Pernos", "Perno de Anclaje", None,
      {"diametro": '1/2"', "largo": '5.1/2"'}),
    R("Perno", "Perno anclaje 3/8x5", "Pernos", "Perno de Anclaje", None,
      {"diametro": '3/8"', "largo": '5"'}),
    R("Perno", "Perno ojo con tuerca 1/2x4, zincado", "Pernos", "Perno Ojo", "Acero galvanizado",
      {"diametro": '1/2"', "largo": '4"'}),
    R("Perno", "Perno de 12x50 C/T", "Pernos", "Perno", None,
      {"diametro": "12mm", "largo": "50mm"}),
    R("Tuerca", "Tuerca hexagonal metrica M8", "Tuercas", "Tuerca", None, {"diametro": "8mm"},
      specs={"rosca": "M8"}),
    R("Tuerca", "Tuerca hexagonal zincada 1/2-13", "Tuercas", "Tuerca", "Acero galvanizado",
      {"diametro": '1/2"'}),
    R("Tuerca", 'Tuerca inoxidable 1/4"', "Tuercas", "Tuerca", "Acero inoxidable",
      {"diametro": '1/4"'}),
    R("Tuerca", "Tuerca hexagonal G-2 zinc UNC 1.1/4", "Tuercas", "Tuerca", "Acero galvanizado",
      {"diametro": '1.1/4"'}, specs={"grado": "G-2", "rosca": "UNC"}),
    R("Tuerca", "Tuerca acero 3/4", "Tuercas", "Tuerca", "Acero carbono", {"diametro": '3/4"'}),
    R("Golilla", 'Golilla presión acero zincado 5/8"', "Golillas", "Golilla de Presión",
      "Acero galvanizado", {"diametro": '5/8"'}),
    R("Golilla plana", "Golilla plana calibrada (03) 5/8 plg", "Golillas", "Golilla Plana", None,
      {"diametro": '5/8"'}),
    R("Golilla", "Golilla plana corriente zinc 1.1/4", "Golillas", "Golilla Plana",
      "Acero galvanizado", {"diametro": '1.1/4"'}),
    R("Hilo", "Hilo por metro zinc 1/2-13", "Varillas y Hilos", "Varilla Roscada",
      "Acero galvanizado", {"diametro": '1/2"'}),
    R("Hilo (varilla roscada)", 'Hilo (varilla) galvanizada 3/4" grado 2, por metro',
      "Varillas y Hilos", "Varilla Roscada", "Acero galvanizado", {"diametro": '3/4"'}),
    R("Remache", "Remache pop 4.8x15", "Remaches", "Remache", None,
      {"diametro": "4.8mm", "largo": "15mm"}),
    R("Remache", "Remache pop de aluminio 4,8 x 10 mm (presentación 1.000)", "Remaches",
      "Remache", "Aluminio", {"diametro": "4.8mm", "largo": "10mm"}),
    R('Remache 3/16"x3/8" 50 pza fiero cab. alum.', "", "Remaches", "Remache", "Acero carbono",
      {"diametro": '3/16"', "largo": '3/8"'}),
    R("Tornillo madera", 'Tornillo madera punta fina #8-9 x 3" para drywall (100 un)',
      "Tornillos", "Tornillo para Madera", None, {"largo": '3"'}),
    R("Autoperforante", 'Autoperforante hex punta broca 12x3/4" (100 un.)', "Tornillos",
      "Tornillo Autoperforante", None, {"largo": '3/4"'}),
    R("Tornillo", 'Tornillo hexagonal SR12-14x1.1/2" (paquete 100 un.)', "Tornillos", "Tornillo",
      None, {"largo": '1.1/2"'}),
    R("Grillete", "Grillete recto 5/16", "Izaje y Amarre", "Grillete", None,
      {"diametro": '5/16"'}),
    R("Cable de acero", 'Cable de acero 8x19, 3/16", 1m', "Izaje y Amarre", "Cable de Acero",
      "Acero carbono", {"diametro": '3/16"', "largo": "1000mm"}),
    R("Cadena", "Cadena eslabon largo 8mm", "Izaje y Amarre", "Cadena", None,
      {"diametro": "8mm"}),
    R("Llave de cadena", "Llave cadena liviana Super Ego 4 plg", "Llaves", "Llave de Cadena",
      None, categoria="Herramientas Manuales"),

    # ------------------------------------------------------------ Eléctricos
    R("Adaptador", "Adaptador Schuko", "Accesorios Eléctricos", "Adaptador Eléctrico",
      categoria="Materiales Eléctricos"),
    R("Adaptador", "Adaptador duplex con Schuko 16A", "Accesorios Eléctricos",
      "Adaptador Eléctrico", categoria="Materiales Eléctricos", specs={"corriente": "16 A"}),
    R("Enchufe hembra", "Enchufe hembra 2P+T 10A blanco", "Accesorios Eléctricos", "Enchufe",
      specs={"corriente": "10 A"}),
    R("Extensión eléctrica", "Extensión Halux de 20 metros", "Cables y Extensiones",
      "Extensión Eléctrica", None, {"largo": "20000mm"}),
    R("Tubo PVC conduit 16mm 3mt (41365)", "Cod. TUB0480", "Conduit", "Conduit", "PVC",
      {"diametro": "16mm", "largo": "3000mm"}),
    R("Cinta eléctrica", "Cinta eléctrica 19mm x 20mt", "Cintas", "Cinta Eléctrica", None,
      {"ancho": "19mm", "largo": "20000mm"}),
    R("Contactor", "Contactor 25A AC3 bobina 230VcA 1NA", "Control", "Contactor",
      specs={"corriente": "25 A"}),

    # ------------------------------------------------------------ Aislación
    R("Coquilla aislante", "Coquilla Aiscom espesor 25mm Ø54mm x 2mt", "Aislación", "Coquilla",
      None, {"espesor": "25mm", "diametro": "54mm", "largo": "2000mm"}),
    R("Coquilla aislante", "Coquilla Aiscom espesor 25mm Ø67mm x 2mt", "Aislación", "Coquilla",
      None, {"espesor": "25mm", "diametro": "67mm", "largo": "2000mm"}),
    R("Manta fibra cerámica", "Manta fibra cerámica 7200x610x25mm, 96kg/m3", "Aislación", "Manta",
      "Fibra cerámica", {"espesor": "25mm", "ancho": "610mm", "largo": "7200mm"}),
    R("Cinta aluminio", "Cinta aluminio 30 micrones 50mmx50mt", "Aislación", "Cinta de Aluminio",
      "Aluminio", {"ancho": "50mm", "largo": "50000mm"}),
    R("Espuma aislante", "Espuma aislante térmica elástica 1 1/2x2mt, cod. CAN2276", "Aislación",
      "Aislante", None, {"diametro": '1.1/2"', "largo": "2000mm"}),
    R("Aerotape", "Aerotape Aiscom 10m x 50mm x 3mm", "Aislación", "Cinta Aislante Térmica", None,
      {"ancho": "50mm", "espesor": "3mm", "largo": "10000mm"}),
    R("Huincha p/ductos alta temp. 0.19mmx48mmx10mt", "", "Aislación", "Cinta de Aluminio", None,
      {"espesor": "0.19mm", "ancho": "48mm", "largo": "10000mm"}),
    R("Concreto refractario", "Concreto refractario convencional 90%, 125 kg", "Aislación",
      "Refractario"),

    # ------------------------------------------------------------ Resto del catálogo
    R("Disco de corte", "Disco de corte 115x1x22,23mm", "Discos", "Disco de Corte", None,
      {"diametro": "115mm", "espesor": "1mm"}),
    R("Disco de corte", 'Disco de corte 7" x 1,6 mm Nexxo Premium', "Discos", "Disco de Corte",
      None, {"diametro": '7"', "espesor": "1.6mm"}),
    R("Disco de corte", "Disco de corte acero inoxidable 2331, 4.1/2 plg", "Discos",
      "Disco de Corte", None, {"diametro": '4.1/2"'}),
    R("Electrodo", "Electrodo 7018 1/8 5kg Bauker", "Electrodos", "Electrodo", None,
      {"diametro": '1/8"'}, specs={"norma": "AWS E7018"}),
    R("Electrodo", "Electrodo E6011 3.2mm 1kg", "Electrodos", "Electrodo", None,
      {"diametro": "3.2mm"}, specs={"norma": "AWS E6011"}),
    R("Broca", "Broca p/metal HSS 12mm", "Brocas", "Broca", "Acero rápido (HSS)",
      {"diametro": "12mm"}),
    R("Brocha", 'Brocha Nexxo Retail Monoblock 4"x12mm', "Brochas y Rodillos", "Brocha", None,
      {"ancho": '4"'}),
    R("Visor", "Visor policarbonato c/marco aluminio 8x16 MY", "Protección Visual",
      "Lente de Seguridad", "Policarbonato"),
    R("Mazo de goma", "Mazo de goma con mango de acero, 16 oz", "Martillos y Mazos", "Martillo",
      "Caucho"),
    R("Adhesivo epoxico", "Adhesivo epoxico para acero, caja azul", "Adhesivos", "Adhesivo",
      "Epoxi"),
    R("Bolsas basura 98x114cm 5 unid. c/amarra 35mic", "venta exenta", "Bolsas y Sacos", "Bolsa",
      None, categoria="Aseo y Oficina"),
    R('Kit bomba DAB circuladora rotor humedo A 80/180XM union 1.1/4" 220V', "Cod. 00.018.09",
      "Bombas", "Bomba", None, categoria="Bombas y Equipos Hidráulicos"),
    R("Pinza", "Pinza porta electrodo 300a", "Accesorios de Soldadura", "Pinza Portaelectrodo",
      categoria="Soldadura y Gases"),
    R("Martillo soldador", "Martillo soldador 500W", "Soldadores y Cautines", "Cautín",
      categoria="Herramientas Eléctricas"),
    R("Manifold", "Manifold tripleauto (manómetro triple para gas/refrigeración)",
      "Instrumentación", "Manifold de Refrigeración", categoria="Instrumentación y Medición"),
    R("Porta sierra copa 14-30 mm 630C Bahco", "Cod. 1606", "Accesorios de Corte",
      "Porta Sierra Copa", categoria="Abrasivos y Corte"),
    R("Adaptador c/broca piloto 11mm (7/16) D-51253", "Cod. ADA1092", "Accesorios de Corte",
      "Porta Sierra Copa", categoria="Abrasivos y Corte"),
    R("Llave de impacto", "Llave de impacto inalámbrica 1/2 20V", "Llaves de Impacto",
      "Llave de Impacto", categoria="Herramientas Eléctricas"),
    R("Barrote", 'Barrote fuerza articulado 1/2" x 15" - Force 8014380 06807150FO',
      "Dados y Puntas", "Barrote de Fuerza", categoria="Herramientas Manuales"),
    R("Pomel", "Pomel de acero con golilla 1 x 4 3/4", "Herrajes", "Pomel", "Acero carbono",
      categoria="Fijaciones"),
    R("Argolla", "Argolla 6x40", "Izaje y Amarre", "Argolla", categoria="Fijaciones"),
    R("Inyector", "Inyector 300-60B", "Quemadores", "Inyector",
      categoria="Calefacción y Combustión"),
    R("Cabezal de terraja", 'Cabezal de terraja de 3/4" NPT, marca Smart Tools', "Terrajas",
      "Terraja", None, {"diametro": '3/4"'}, categoria="Herramientas Manuales"),
    R("Termopozo", 'Termopozo SS316 niple/tubo PN40 1/2"NPT F x 1/2"NPT M, largo 100mm, '
      "tubo Ø8,5mm", "Instrumentación", "Termopozo", "Acero inoxidable",
      # En un instrumento la medida que lo identifica es su CONEXION (el
      # 1/2" NPT); el Ø8,5 mm es el tubo de la vaina.
      {"conexion": '1/2"', "largo": "100mm"}, specs={"grado": "AISI 316"}),
    R("Manometro", 'Manómetro Tempres DN4" (100mm) 0-200 PSI/0-14 BAR, caja inox SS304, '
      'conexión inferior 1/2" NPT bronce, glicerina', "Instrumentación", "Manómetro",
      "Acero inoxidable", specs={"grado": "AISI 304"}),
    R("Anodo de magnesio", "Ánodo de magnesio terminal, diámetro 26mm, largo 500mm, soporte 1, "
      "código 26x500T-2605", "Ánodos", "Ánodo", "Magnesio",
      {"diametro": "26mm", "largo": "500mm"}),
]
